import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../globals.css'
import SessionProvider from '@/components/session_provider'
import Nav from '@/components/nav/nav'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${poppins.className} relative h-full font-sans antialiased`}
      >
        <SessionProvider>
          <Nav />
          <main className="flex flex-col min-h-screen relative pt-20">
            <div className="flex-grow flex-1">{children}</div>
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
